### ISSUE TITLE
Describe data and original dataset

### ISSUE THREAD

**Issue by espinielli** [eurostat/euronym#1]
It would be great to have README or other explain where the data is extracted from (the Java code points at some GISCO file on local machine, but probably a public online version is available too) and what the output structure is like, i.e. what `rs` and `r1` are (`name`, `lon` and `lat` are guessable :smile: )

**Comment by jgaffuri** [comment]
This will be documented... soon !

**Comment by jgaffuri** [comment]
The documentation is there - let me know if it is sufficient !
